# Generated by Django 4.2.28 on 2026-02-26 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('puesto', 'Puesto'), ('sala', 'Sala')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permite_sala', models.BooleanField(default=False)),
                ('limite_horas_mensuales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=150)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=255)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('vigente_hasta', models.DateTimeField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.espacio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Analitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('horas_ocupadas', models.IntegerField()),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.espacio')),
            ],
        ),
    ]
